---
# tasks file for lb
   - name: install haproxy
      yum:
        name: haproxy
        state: latest
        update_cache: true
    - name: start and enable service
      service:
        name: haproxy
        state: started
        enabled: yes

    - name: call template
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0640
        owner: root
        group: root
      notify: restart haproxy



