---
# tasks file for common

    - name: update /etc/hosts file
      lineinfile:
        path: "{{ hostsfile }}"
        regexp: "{{ item }}$"
        line: "{{ hostvars[item].ansible_facts.eth1.ipv4.address }} {{ hostvars[item].ansible_facts.hostname }}.{{ domainname }} {{ hostvars[item].ansible_facts
.hostname }}"
      loop: "{{ groups['all'] }}"

    - name: install packages
      yum:
        name:
          - firewalld
          - ntp
        state: present
        update_cache: true

    - name: install ntp template
      template:
        src: ntp.j2.conf
        dest: "{{ ntp_conf_file }}"
      notify: restart ntp
    - name: start and enable service
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - ntpd
        - firewalld



