---

- hosts: web1
  gather_facts: false
  vars:
    var1: 'set-via-vars-in-playbook'
  tasks:
    - name: task 1
      debug:
        msg: "{{ var1 }}"
    - name: task 2
      set_fact:
        var1: 'set-via-set-fact'
    - name: task 3
      debug:
        msg: "{{ var1 }}"
