---
    - name: install apache
      yum:
        name:
          - httpd
          - php
          - php-mysql
          - git
        state: present
        update_cache: true
      tags:
        - base

    - name: start apache service
      service:
        name: httpd
        state: started
        enabled: true
      tags:
        - base
    - name: deploy index.php
      get_url:
        url: "{{ repo_url }}"
        dest: "{{ document_root_path }}"
      tags:
        - content
    - name: vhost config block
      block:
      - name: Copy host config
        copy:
          src: ansible_site.conf
          dest: "{{ vhost_config_file }}"
          owner: root
          mode: '0644'
          backup: true
        notify: restart apache
      - name: check config validity
        command: httpd -t
      rescue:
      - name: remove bad config file
        file:
          path: "{{ vhost_config_file }}"
          state: absent
      - name: rolling back -ending playbook
        fail:
          msg: " Config file vlaidity check has failed. Please corret the configfile before running playbook again"
      tags:
        - vhost
    - name: Add load config file line
      lineinfile:
        path: "{{ apache_config_file }}"
        regexp: '^IncludeOptional'
        line: "IncludeOptional conf.d/*.conf"
      notify: restart apache
      tags:
        - content

    - name: Install hello world script with db
      copy:
        src: db.php
        dest: "{{ document_root_path }}"
        mode: 0775
      tags:
        - content
    - name: disable selinux
      selinux:
        state: disabled
      tags:
        - security


