---

- hosts: web
  gather_facts: false
  become: yes
  vars_prompt:
  - name: "version"
    prompt: "Which version do you want to install?"
    private: no
    default: "2.4.6"
  tasks:
  - name: debug task
    debug:
      msg: "Will install httpd-{{ version }}"
  - name: 
    yum:
      name: "httpd-{{ version }}"
      state: present 
